    - name: Scarica ed Installa Gradle 8.4 Ufficiale
      run: |
        wget https://gradle.org
        sudo unzip -d /opt/gradle gradle-8.4-bin.zip
        echo "/opt/gradle/gradle-8.4/bin" >> $GITHUB_PATH

    - name: Compila APK Eseguibile
      run: gradle assembleDebug

    - name: Carica l'APK Pronto da Installare
      uses: actions/upload-artifact@v4
      with:
        name: App-Linea-Verde-Installabile
        path: "**/build/outputs/apk/debug/*.apk"
